// Selected database adapter. Exact source values and explicit transaction calls
// are kept separate from business functions. Record-only mode is a contract test.
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;

public sealed class MfDatabase : IDisposable {
    public const string TARGET="sqlite";
    readonly Dictionary<string,object> payload,schema;readonly bool contract;
    public readonly List<object> operations=new();DbConnection conn;DbTransaction transaction;
    bool pending,uncertain;string session;
    public MfDatabase(Dictionary<string,object> p){payload=p;schema=MfRuntime.obj(p["schema"]);contract=(string)p.GetValueOrDefault("execution_mode","")=="contract";if((string)p["database"]!=TARGET)throw new ArgumentException("Context database differs from generated target");if(!contract&&MfRuntime.list(p["capability_blockers"]).Count>0)throw new ArgumentException("Unresolved target capability blockers");if(!contract&&TARGET!="sqlite"&&!Equals(p.GetValueOrDefault("allow_remote",false),true))throw new ArgumentException("Remote execution is not enabled");}
    string env(string key){var config=MfRuntime.obj(MfRuntime.obj(payload["connections"])[TARGET]);string name=(string)config[key],value=Environment.GetEnvironmentVariable(name);if(string.IsNullOrEmpty(value))throw new ArgumentException("Required environment variable missing: "+name);return value;}
    string identifier(string name){if(!Regex.IsMatch(name,@"^[A-Z][A-Z0-9_]{0,127}$"))throw new ArgumentException("Unsafe SQL identifier");return TARGET=="bigquery"?"`"+name+"`":"\""+name+"\"";}
    object exact(Dictionary<string,object> c,object value){if(value==null){if(!Equals(c["nullable"],true))throw new ArgumentException("NULL violates source schema");return null;}
        string kind=(string)c["kind"];if(kind=="text"){if(value is not string s)throw new ArgumentException("Text differs from source type");int length=MfRuntime.integer(c["length"]);if(s.Length>length)throw new ArgumentException("Text exceeds source width");if(TARGET=="oracle"&&s.Length==0)throw new ArgumentException("Oracle empty-string mapping unresolved");return (string)c["source_type"]=="CHAR"?MfRuntime.pad(s,length):s;}
        var n=MfRuntime.num(value);if(kind=="integer"){if(!n.IsInteger||n.CompareTo(Dec.Parse((string)c["minimum"]))<0||n.CompareTo(Dec.Parse((string)c["maximum"]))>0)throw new ArgumentException("Integer violates source bounds");return n.ToInt64();}
        int scale=MfRuntime.integer(c["scale"]),precision=MfRuntime.integer(c["precision"]);var limit=Dec.Parse("1"+new string('0',precision-scale));if(n.CompareTo(limit)>=0||n.CompareTo(Dec.Parse("-"+limit.ToString()))<=0)throw new ArgumentException("Decimal exceeds source precision");return n.Fixed(scale);}
    // Drivers must be supplied through the approved package feed. Never fall back to another DB.
    void connect(){if(conn!=null)return;string type=TARGET=="sqlite"?"Microsoft.Data.Sqlite.SqliteConnection, Microsoft.Data.Sqlite":"Oracle.ManagedDataAccess.Client.OracleConnection, Oracle.ManagedDataAccess";var provider=Type.GetType(type,throwOnError:true);conn=(DbConnection)Activator.CreateInstance(provider);var builder=new DbConnectionStringBuilder();if(TARGET=="sqlite"){builder["Data Source"]=Path.Combine((string)payload["work_root"],"local.sqlite");builder["Foreign Keys"]=true;}else{builder["Data Source"]=env("dsn_env");builder["User Id"]=env("user_env");builder["Password"]=env("password_env");}conn.ConnectionString=builder.ConnectionString;conn.Open();}
    Dictionary<string,object> child(Dictionary<string,object> m,string key)=>m.TryGetValue(key,out var x)&&x is Dictionary<string,object> d?d:new Dictionary<string,object>();
    Dictionary<string,object> wire(string method,string url,object body){using var client=new HttpClient{Timeout=TimeSpan.FromSeconds(30)};using var request=new HttpRequestMessage(new HttpMethod(method),url);request.Headers.Authorization=new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer",env("token_env"));if(body!=null)request.Content=new StringContent(Json.Dump(body),Encoding.UTF8,"application/json");using var response=client.Send(request);if(!response.IsSuccessStatusCode)throw new IOException("BigQuery HTTP "+(int)response.StatusCode+"; inspect recorded job ID");return MfRuntime.obj(Json.Parse(response.Content.ReadAsStringAsync().GetAwaiter().GetResult()));}
    // Run explicit BigQuery session jobs and retain identity before any network mutation.
    Dictionary<string,object> query(string sql,List<object> parameters,bool create){string project=env("project_env"),dataset=env("dataset_env"),location=env("location_env");if(!Regex.IsMatch(project,@"^[A-Za-z0-9_-]+$")||!Regex.IsMatch(dataset,@"^[A-Za-z0-9_]+$")||!Regex.IsMatch(location,@"^[A-Za-z0-9_-]+$"))throw new ArgumentException("Invalid BigQuery identifiers");string id="migration_"+Guid.NewGuid().ToString("N"),baseUrl="https://bigquery.googleapis.com/bigquery/v2/projects/"+project+"/jobs";
        var q=new Dictionary<string,object>{{"query",sql},{"useLegacySql",false},{"defaultDataset",new Dictionary<string,object>{{"projectId",project},{"datasetId",dataset}}}};
        if(parameters.Count>0){q["parameterMode"]="NAMED";q["queryParameters"]=parameters;}if(create)q["createSession"]=true;else if(session!=null)q["connectionProperties"]=new[]{new Dictionary<string,object>{{"key","session_id"},{"value",session}}};
        var body=new Dictionary<string,object>{{"jobReference",new Dictionary<string,object>{{"projectId",project},{"jobId",id},{"location",location}}},{"configuration",new Dictionary<string,object>{{"query",q},{"jobTimeoutMs","60000"}}}};
        File.AppendAllText(Path.Combine((string)payload["work_root"],"remote_job_ids.jsonl"),System.Text.Json.JsonSerializer.Serialize(new{job_id=id,session_id=session,operation=sql.Split(' ')[0]})+"\n");
        Dictionary<string,object> result;
        try{result=wire("POST",baseUrl,body);if(create&&child(child(result,"statistics"),"sessionInfo").TryGetValue("sessionId",out var sid))session=(string)sid;var timer=System.Diagnostics.Stopwatch.StartNew();while(!Equals(child(result,"status").GetValueOrDefault("state"),"DONE")){if(timer.Elapsed.TotalSeconds>60)throw new IOException("Remote outcome unknown; no retry is made");Thread.Sleep(250);result=wire("GET",baseUrl+"/"+id+"?location="+location,null);}if(create&&child(child(result,"statistics"),"sessionInfo").TryGetValue("sessionId",out var sid2))session=(string)sid2;}catch{uncertain=true;throw;}
        if(child(result,"status").ContainsKey("errorResult"))throw new IOException("BigQuery rejected the recorded job");if(create&&session==null)throw new IOException("Session identifier missing");return result;}
    public void insert(string table,string[] columns,object[] values){if(columns.Length!=values.Length||columns.Distinct().Count()!=columns.Length)throw new ArgumentException("INSERT mapping differs");var defs=MfRuntime.obj(MfRuntime.obj(schema[table])["columns"]);var bound=new List<object>();for(int i=0;i<columns.Length;i++)bound.Add(exact(MfRuntime.obj(defs[columns[i]]),values[i]));operations.Add(new Dictionary<string,object>{{"op","insert"},{"table",table},{"columns",columns},{"values",bound}});if(contract){pending=true;return;}
        var names=columns.Select(identifier).ToArray();var tokens=Enumerable.Range(0,columns.Length).Select(i=>TARGET=="oracle"?":p"+i:"@p"+i);string sql="INSERT INTO "+identifier(table)+" ("+string.Join(",",names)+") VALUES ("+string.Join(",",tokens)+")";
        if(TARGET=="bigquery"){if(!pending)query("BEGIN TRANSACTION;",new List<object>(),session==null);pending=true;var parameters=new List<object>();for(int i=0;i<columns.Length;i++){var c=MfRuntime.obj(defs[columns[i]]);string kind=(string)c["kind"],typ=kind=="integer"?"INT64":kind=="text"?"STRING":MfRuntime.integer(c["scale"])<=9&&MfRuntime.integer(c["precision"])-MfRuntime.integer(c["scale"])<=29?"NUMERIC":"BIGNUMERIC";var v=new Dictionary<string,object>();if(bound[i]!=null)v["value"]=bound[i].ToString();parameters.Add(new Dictionary<string,object>{{"name","p"+i},{"parameterType",new Dictionary<string,object>{{"type",typ}}},{"parameterValue",v}});}query(sql,parameters,false);}
        else{connect();if(transaction==null)transaction=conn.BeginTransaction();pending=true;using var command=conn.CreateCommand();command.Transaction=transaction;command.CommandText=sql;if(TARGET=="oracle")command.GetType().GetProperty("BindByName")?.SetValue(command,true);
            for(int i=0;i<columns.Length;i++){var c=MfRuntime.obj(defs[columns[i]]);string kind=(string)c["kind"];var p=command.CreateParameter();p.ParameterName="p"+i;if(bound[i]==null){p.DbType=kind=="text"?DbType.String:DbType.Decimal;p.Value=DBNull.Value;}else if(kind=="integer"){p.DbType=DbType.Int64;p.Value=bound[i];}else if(kind=="decimal"&&TARGET=="oracle"){var t=Type.GetType("Oracle.ManagedDataAccess.Types.OracleDecimal, Oracle.ManagedDataAccess",throwOnError:true);var parse=t.GetMethod("Parse",new[]{typeof(string)})??throw new InvalidOperationException("Oracle decimal API not available in installed driver");p.Value=parse.Invoke(null,new[]{bound[i]});}else{p.DbType=DbType.String;p.Value=bound[i];}command.Parameters.Add(p);}command.ExecuteNonQuery();}}
    public void commit(){operations.Add(new Dictionary<string,object>{{"op","commit"}});if(!contract){if(TARGET=="bigquery"&&pending)query("COMMIT TRANSACTION;",new List<object>(),false);else if(transaction!=null){transaction.Commit();transaction.Dispose();transaction=null;}}pending=false;}
    public void rollback(){operations.Add(new Dictionary<string,object>{{"op","rollback"}});if(!contract){if(TARGET=="bigquery"&&pending)query("ROLLBACK TRANSACTION;",new List<object>(),false);else if(transaction!=null){transaction.Rollback();transaction.Dispose();transaction=null;}}pending=false;}
    public void finish(){if(pending){rollback();throw new InvalidOperationException("Source ended with an uncommitted transaction; no commit was added");}}
    public void Dispose(){if(pending&&!uncertain)rollback();conn?.Dispose();if(TARGET=="bigquery"&&session!=null&&!contract&&!uncertain){query("CALL BQ.ABORT_SESSION();",new List<object>(),false);session=null;}}
}
